-- O PLANO DE CONTAS DA PRATICA (499 contas).
--
-- ---------------------------------------------------------------------------
-- POR QUE ISTO SUBSTITUI, E NAO ACRESCENTA
--
-- O sistema nasceu com 41 contas de arranque — o minimo para o motor ter onde
-- lancar. O escritorio usa outro plano, de 499 contas, que e o que eles
-- conhecem e o que sai nos relatorios que ja entregam aos clientes.
--
-- Ter os dois seria pior do que qualquer um deles: 540 contas no seletor, com
-- duas "Sales" e dois "Trade debtors", e ninguem a saber em qual lancar.
--
-- As antigas NAO SAO APAGADAS — ficam inativas. Apagar partiria qualquer linha
-- de razao que eu nao tenha remapeado, e a partiria em silencio: uma partida
-- que aponta para uma conta que nao existe nao da erro, so desaparece dos
-- relatorios.
-- ---------------------------------------------------------------------------

-- 1. AS CONTAS NOVAS ------------------------------------------------------
insert into chart_of_accounts (code, description, type, report_group, parent_code, postable)
values
  ('001', 'Sales', 'revenue', 'turnover', null, true),
  ('001.01', 'Sales type B', 'revenue', 'turnover', '001', true),
  ('001.02', 'Sales type C', 'revenue', 'turnover', '001', true),
  ('001.03', 'Sales Type 4', 'revenue', 'turnover', '001', true),
  ('001.04', 'Sales Type 5', 'revenue', 'turnover', '001', true),
  ('002', 'Sales Type 2', 'revenue', 'turnover', null, true),
  ('003', 'Sales Type 3', 'revenue', 'turnover', null, true),
  ('051', 'Rent receivable - sales', 'revenue', 'turnover', null, true),
  ('061', 'Commissions receivable', 'revenue', 'turnover', null, true),
  ('071', 'Fees receivable', 'revenue', 'turnover', null, true),
  ('076', 'Service fees receivable', 'revenue', 'turnover', null, true),
  ('081', 'Other income', 'revenue', 'turnover', null, true),
  ('083', 'Government grant income', 'revenue', 'turnover', null, true),
  ('100', 'Cost of goods sold', 'expense', 'cost_of_sales', null, true),
  ('101', 'Opening Stock (non trading)', 'expense', 'cost_of_sales', null, true),
  ('111', 'Materials', 'expense', 'cost_of_sales', null, true),
  ('112', 'Purchases', 'expense', 'cost_of_sales', null, true),
  ('113', 'Subcontractors', 'expense', 'cost_of_sales', null, true),
  ('114', 'Motor expenses', 'expense', 'cost_of_sales', null, true),
  ('115', 'Travelling and entertainment', 'expense', 'cost_of_sales', null, true),
  ('116', 'Entertaining', 'expense', 'cost_of_sales', null, true),
  ('121', 'Closing stock', 'expense', 'cost_of_sales', null, true),
  ('122', 'Closing stock (non trading)', 'expense', 'cost_of_sales', null, true),
  ('160', 'Legal and Professional fees', 'expense', 'cost_of_sales', null, true),
  ('301', 'Wages and salaries', 'expense', 'administrative_expenses', null, true),
  ('302', 'Directors salaries', 'expense', 'administrative_expenses', null, true),
  ('303', 'Employers NIC (UK) PRSI (Ireland)', 'expense', 'administrative_expenses', null, true),
  ('304', 'Pension costs', 'expense', 'administrative_expenses', null, true),
  ('305', 'Staff defined contribution pension costs', 'expense', 'administrative_expenses', null, true),
  ('306', 'Pensions paid to former directors', 'expense', 'administrative_expenses', null, true),
  ('307', 'Directors'' fees', 'expense', 'administrative_expenses', null, true),
  ('308', 'Compensation for loss of office', 'expense', 'administrative_expenses', null, true),
  ('308.01', 'Staff compensation for loss of office', 'expense', 'administrative_expenses', '308', true),
  ('309', 'Staff training', 'expense', 'administrative_expenses', null, true),
  ('310', 'Sums paid to third parties', 'expense', 'administrative_expenses', null, true),
  ('319', 'Commissions', 'expense', 'administrative_expenses', null, true),
  ('320', 'Use of premises', 'expense', 'administrative_expenses', null, true),
  ('321', 'Operating lease rentals - land and buildings', 'expense', 'administrative_expenses', null, true),
  ('322', 'Rent payable', 'expense', 'administrative_expenses', null, true),
  ('323', 'Rates', 'expense', 'administrative_expenses', null, true),
  ('325', 'Service charges', 'expense', 'administrative_expenses', null, true),
  ('326', 'Insurance', 'expense', 'administrative_expenses', null, true),
  ('327', 'Leasing of plant and machinery', 'expense', 'administrative_expenses', null, true),
  ('328', 'Leasing of office equipment', 'expense', 'administrative_expenses', null, true),
  ('330', 'Computer bureau costs', 'expense', 'administrative_expenses', null, true),
  ('331', 'Light and heat', 'expense', 'administrative_expenses', null, true),
  ('332', 'Cleaning', 'expense', 'administrative_expenses', null, true),
  ('334', 'Repairs and maintenance', 'expense', 'administrative_expenses', null, true),
  ('341', 'Printing, postage and stationery', 'expense', 'administrative_expenses', null, true),
  ('342', 'Advertising', 'expense', 'administrative_expenses', null, true),
  ('343', 'Courier and Delivery Charges', 'expense', 'administrative_expenses', null, true),
  ('345', 'Telephone  Broadband', 'expense', 'administrative_expenses', null, true),
  ('346', 'Computer costs', 'expense', 'administrative_expenses', null, true),
  ('347', 'Hire of equipment', 'expense', 'administrative_expenses', null, true),
  ('349', 'Motor vehicle leasing', 'expense', 'administrative_expenses', null, true),
  ('351', 'Motor expenses', 'expense', 'administrative_expenses', null, true),
  ('361', 'Travelling and entertainment', 'expense', 'administrative_expenses', null, true),
  ('362', 'Entertaining', 'expense', 'administrative_expenses', null, true),
  ('363', 'Development expenditure written off', 'expense', 'administrative_expenses', null, true),
  ('364', 'Research expenditure written off', 'expense', 'administrative_expenses', null, true),
  ('365', 'Legal and professional', 'expense', 'administrative_expenses', null, true),
  ('367', 'Consultancy fees', 'expense', 'administrative_expenses', null, true),
  ('368', 'Accountancy Fees', 'expense', 'administrative_expenses', null, true),
  ('369', 'Audit', 'expense', 'administrative_expenses', null, true),
  ('369.01', 'Auditor''s remuneration - other assurance services', 'expense', 'administrative_expenses', '369', true),
  ('369.02', 'Auditor''s remuneration - tax advisory services', 'expense', 'administrative_expenses', '369', true),
  ('369.03', 'Auditor''s remuneration - other non-audit services', 'expense', 'administrative_expenses', '369', true),
  ('369.04', 'Auditor''s remuneration - audit-related assurance services', 'expense', 'administrative_expenses', '369', true),
  ('369.05', 'Auditor''s remuneration - taxation compliance services', 'expense', 'administrative_expenses', '369', true),
  ('369.06', 'Auditor''s remuneration - internal audit services', 'expense', 'administrative_expenses', '369', true),
  ('369.07', 'Auditor''s remuneration - other corporate finance transactions services', 'expense', 'administrative_expenses', '369', true),
  ('369.08', 'Auditor''s remuneration - audit of subsidiaries and associates', 'expense', 'administrative_expenses', '369', true),
  ('370', 'Factoring charges', 'expense', 'administrative_expenses', null, true),
  ('371', 'Bank charges', 'expense', 'administrative_expenses', null, true),
  ('372', 'Credit card charges', 'expense', 'administrative_expenses', null, true),
  ('373', 'Bad debts', 'expense', 'administrative_expenses', null, true),
  ('374', 'Doubtful debts', 'expense', 'administrative_expenses', null, true),
  ('375', 'Discounts allowed', 'expense', 'administrative_expenses', null, true),
  ('376', 'Discounts received', 'expense', 'administrative_expenses', null, true),
  ('377', 'Profit/loss on exchange', 'expense', 'administrative_expenses', null, true),
  ('378', 'Canteen', 'expense', 'administrative_expenses', null, true),
  ('379', 'Staff welfare', 'expense', 'administrative_expenses', null, true),
  ('380', 'Impairment of short-term debtors', 'expense', 'administrative_expenses', null, true),
  ('380.01', 'Impairment of short-term creditors', 'expense', 'administrative_expenses', '380', true),
  ('381', 'General expenses', 'expense', 'administrative_expenses', null, true),
  ('383', 'Charitable donations - covenanted', 'expense', 'administrative_expenses', null, true),
  ('384', 'Charitable donations - other', 'expense', 'administrative_expenses', null, true),
  ('385', 'Political donations', 'expense', 'administrative_expenses', null, true),
  ('391', 'Depreciation of intangible assets', 'expense', 'administrative_expenses', null, true),
  ('391.03', 'Amortisation of goodwill', 'expense', 'administrative_expenses', '391', true),
  ('392', 'Depreciation of tangible assets', 'expense', 'administrative_expenses', null, true),
  ('392.01', 'Impairment of freehold property', 'expense', 'administrative_expenses', '392', true),
  ('392.02', 'Reversal of impairment losses of freehold property', 'expense', 'administrative_expenses', '392', true),
  ('392.03', 'Depreciation of investment property', 'expense', 'administrative_expenses', '392', true),
  ('393', 'Amortisation of long leasehold', 'expense', 'administrative_expenses', null, true),
  ('394', 'Amortisation of short leasehold', 'expense', 'administrative_expenses', null, true),
  ('395', 'Depreciation of plant and machinery', 'expense', 'administrative_expenses', null, true),
  ('396', 'Depreciation on fixtures, fittings and equipment', 'expense', 'administrative_expenses', null, true),
  ('397', 'Depreciation of motor vehicles', 'expense', 'administrative_expenses', null, true),
  ('398', 'Depreciation of user-defined assets', 'expense', 'administrative_expenses', null, true),
  ('399', 'Profits/losses on disposal of intangibles', 'expense', 'administrative_expenses', null, true),
  ('399.01', 'Profits/losses on disposal of tangibles', 'expense', 'administrative_expenses', '399', true),
  ('455', 'Exceptional provision', 'expense', 'administrative_expenses', null, true),
  ('401', 'Rent receivable', 'revenue', 'other_operating_income', null, true),
  ('402', 'Amortisation of government grants', 'revenue', 'other_operating_income', null, true),
  ('403', 'Government grants received', 'revenue', 'other_operating_income', null, true),
  ('406', 'Service charge receivable', 'revenue', 'other_operating_income', null, true),
  ('407', 'Insurance claims receivable', 'revenue', 'other_operating_income', null, true),
  ('408', 'Sundry income', 'revenue', 'other_operating_income', null, true),
  ('416', 'Other exceptional item 1', 'expense', 'administrative_expenses', null, true),
  ('420', 'Bank interest received', 'revenue', 'interest_and_similar', null, true),
  ('420.01', 'Bank interest receivable accrued', 'revenue', 'interest_and_similar', '420', true),
  ('421', 'Other interest received', 'revenue', 'interest_and_similar', null, true),
  ('422', 'Other interest receivable accrued', 'revenue', 'interest_and_similar', null, true),
  ('427', 'Listed investment interest received', 'revenue', 'interest_and_similar', null, true),
  ('427.01', 'Listed investment interest receivable', 'revenue', 'interest_and_similar', '427', true),
  ('429', 'Unlisted investment interest received', 'revenue', 'interest_and_similar', null, true),
  ('429.01', 'Unlisted investment interest receivable', 'revenue', 'interest_and_similar', '429', true),
  ('431', 'Dividends received from subsidiary undertakings', 'revenue', 'interest_and_similar', null, true),
  ('431.02', 'Dividends from listed investments', 'revenue', 'interest_and_similar', '431', true),
  ('431.03', 'Dividends from unlisted investments', 'revenue', 'interest_and_similar', '431', true),
  ('435', 'Other investment income', 'revenue', 'interest_and_similar', null, true),
  ('442.02', 'Profit/Loss on disposal of interests in subsidiaries', 'revenue', 'interest_and_similar', '442', true),
  ('461', 'Interest paid to group companies', 'expense', 'interest_and_similar', null, true),
  ('461.01', 'Interest payable to group companies accrued', 'expense', 'interest_and_similar', '461', true),
  ('471', 'Bank interest paid and payable', 'expense', 'interest_and_similar', null, true),
  ('472', 'Bank interest paid', 'expense', 'interest_and_similar', null, true),
  ('473', 'Other interest paid on loans < 1 year', 'expense', 'interest_and_similar', null, true),
  ('473.01', 'Other interest accrued on loans < 1 year', 'expense', 'interest_and_similar', '473', true),
  ('475', 'Other interest paid on loans > 1 year < 2 years', 'expense', 'interest_and_similar', null, true),
  ('475.01', 'Other interest accrued on loans > 1 year < 2 years', 'expense', 'interest_and_similar', '475', true),
  ('477', 'Other interest on loans paid > 2 years < 5 years', 'expense', 'interest_and_similar', null, true),
  ('477.01', 'Other interest accrued on loans > 2 years < 5 years', 'expense', 'interest_and_similar', '477', true),
  ('479', 'Other interest paid on loans > 5 years', 'expense', 'interest_and_similar', null, true),
  ('479.01', 'Other interest accrued on loans > 5 years', 'expense', 'interest_and_similar', '479', true),
  ('481', 'Hire purchase interest', 'expense', 'interest_and_similar', null, true),
  ('482', 'Lease finance charges', 'expense', 'interest_and_similar', null, true),
  ('483', 'Factoring interest', 'expense', 'interest_and_similar', null, true),
  ('487', 'Finance charge paid on shares classified as financial liabilities', 'expense', 'interest_and_similar', null, true),
  ('450', 'Fair value gains and losses on investment properties', 'expense', 'interest_and_similar', null, true),
  ('450.01', 'Fair value gains on PPE reversing previous revaluation decrease in profit or loss', 'expense', 'interest_and_similar', '450', true),
  ('450.06', 'Fair value gains and losses on foreign exchange', 'expense', 'interest_and_similar', '450', true),
  ('499', 'Profit and loss suspense', 'expense', 'administrative_expenses', null, true),
  ('501', 'Corporation tax current year', 'expense', 'tax_on_profit', null, true),
  ('501.01', 'Corporation tax adjustment re previous year', 'expense', 'tax_on_profit', '501', true),
  ('503', 'Double taxation relief', 'expense', 'tax_on_profit', null, true),
  ('503.01', 'Income tax', 'expense', 'tax_on_profit', '503', true),
  ('503.02', 'Overseas tax', 'expense', 'tax_on_profit', '503', true),
  ('504', 'Irrecoverable Advance Corporation Tax', 'expense', 'tax_on_profit', null, true),
  ('506', 'Deferred tax charge/credit current year', 'expense', 'tax_on_profit', null, true),
  ('506.01', 'Deferred tax adjustment re previous year', 'expense', 'tax_on_profit', '506', true),
  ('508', 'Prior year adjustment re deferred tax', 'expense', 'tax_on_profit', null, true),
  ('510', 'Capital gains tax', 'expense', 'tax_on_profit', null, true),
  ('511', 'Tax credit', 'expense', 'tax_on_profit', null, true),
  ('606', 'Development cost b/fwd', 'asset', 'fixed_assets_intangible', null, true),
  ('606.01', 'Development cost capitalised', 'asset', 'fixed_assets_intangible', '606', true),
  ('606.02', 'Development cost disposal', 'asset', 'fixed_assets_intangible', '606', true),
  ('606.03', 'Development cost foreign currency exchange difference cost', 'asset', 'fixed_assets_intangible', '606', true),
  ('606.04', 'Development costs transfer to/from other category', 'asset', 'fixed_assets_intangible', '606', true),
  ('607', 'Development cost depreciation b/fwd', 'asset', 'fixed_assets_intangible', null, true),
  ('607.01', 'Development cost depreciation charge for period', 'asset', 'fixed_assets_intangible', '607', true),
  ('607.02', 'Development cost depreciation elimination on disposal', 'asset', 'fixed_assets_intangible', '607', true),
  ('607.03', 'Development cost foreign currency exchange difference provision', 'asset', 'fixed_assets_intangible', '607', true),
  ('611', 'Goodwill cost b/fwd', 'asset', 'fixed_assets_intangible', null, true),
  ('611.01', 'Goodwill additions', 'asset', 'fixed_assets_intangible', '611', true),
  ('611.02', 'Goodwill cost written off to reserves', 'asset', 'fixed_assets_intangible', '611', true),
  ('611.03', 'Goodwill disposal', 'asset', 'fixed_assets_intangible', '611', true),
  ('611.04', 'Goodwill foreign currency exchange difference cost', 'asset', 'fixed_assets_intangible', '611', true),
  ('611.05', 'Goodwill transfer to/from other category', 'asset', 'fixed_assets_intangible', '611', true),
  ('612', 'Goodwill accumulated depreciation b/fwd', 'asset', 'fixed_assets_intangible', null, true),
  ('612.01', 'Goodwill depreciation charge for period', 'asset', 'fixed_assets_intangible', '612', true),
  ('612.02', 'Goodwill depreciation write off to reserves', 'asset', 'fixed_assets_intangible', '612', true),
  ('612.03', 'Goodwill depreciation elimination on disposal', 'asset', 'fixed_assets_intangible', '612', true),
  ('612.04', 'Goodwill foreign currency exchange difference provision', 'asset', 'fixed_assets_intangible', '612', true),
  ('613', 'Goodwill impairments b/fwd', 'asset', 'fixed_assets_intangible', null, true),
  ('613.01', 'Goodwill impairment losses', 'asset', 'fixed_assets_intangible', '613', true),
  ('613.02', 'Goodwill reversals of past losses', 'asset', 'fixed_assets_intangible', '613', true),
  ('621', 'Freehold property', 'asset', 'fixed_assets_tangible', null, true),
  ('621.01', 'Freeholds additions at cost', 'asset', 'fixed_assets_tangible', '621', true),
  ('621.02', 'Freeholds revaluation in period', 'asset', 'fixed_assets_tangible', '621', true),
  ('621.03', 'Freeholds cost or valuation of disposal', 'asset', 'fixed_assets_tangible', '621', true),
  ('621.04', 'Freeholds transfer to/from other category', 'asset', 'fixed_assets_tangible', '621', true),
  ('621.05', 'Freeholds foreign currency exchange difference cost', 'asset', 'fixed_assets_tangible', '621', true),
  ('621.06', 'Freeholds additions accruals', 'asset', 'fixed_assets_tangible', '621', true),
  ('622', 'Depreciation on freehold property', 'asset', 'fixed_assets_tangible', null, true),
  ('622.01', 'Freeholds depreciation charge for period', 'asset', 'fixed_assets_tangible', '622', true),
  ('622.02', 'Freeholds depreciation write back on revaluation', 'asset', 'fixed_assets_tangible', '622', true),
  ('622.03', 'Freeholds depreciation elimination on disposal', 'asset', 'fixed_assets_tangible', '622', true),
  ('622.04', 'Freeholds depreciation transfer to/from other category', 'asset', 'fixed_assets_tangible', '622', true),
  ('622.05', 'Freeholds foreign currency exchange difference depreciation', 'asset', 'fixed_assets_tangible', '622', true),
  ('623', 'Freeholds cost impairments b/fwd', 'asset', 'fixed_assets_tangible', null, true),
  ('623.01', 'Freeholds cost impairment losses', 'asset', 'fixed_assets_tangible', '623', true),
  ('623.02', 'Freeholds cost reversals of past losses', 'asset', 'fixed_assets_tangible', '623', true),
  ('624', 'Freeholds valuation impairments b/fwd', 'asset', 'fixed_assets_tangible', null, true),
  ('624.01', 'Freeholds valuation impairment losses', 'asset', 'fixed_assets_tangible', '624', true),
  ('624.02', 'Freeholds valuation reversal of past losses', 'asset', 'fixed_assets_tangible', '624', true),
  ('626', 'Investment properties cost or valuation b/fwd', 'asset', 'fixed_assets_tangible', null, true),
  ('626.01', 'Investment properties additions at cost', 'asset', 'fixed_assets_tangible', '626', true),
  ('626.02', 'Investment properties revaluation in period', 'asset', 'fixed_assets_tangible', '626', true),
  ('626.03', 'Investment properties cost or valuation of disposal', 'asset', 'fixed_assets_tangible', '626', true),
  ('626.04', 'Investment properties transfer to/from other category', 'asset', 'fixed_assets_tangible', '626', true),
  ('626.05', 'Investment properties foreign currency exchange difference cost', 'asset', 'fixed_assets_tangible', '626', true),
  ('626.06', 'Investment properties additions accruals', 'asset', 'fixed_assets_tangible', '626', true),
  ('627', 'Investment properties valuation impairments b/fwd', 'asset', 'fixed_assets_tangible', null, true),
  ('627.01', 'Investment properties valuation impairment losses', 'asset', 'fixed_assets_tangible', '627', true),
  ('627.02', 'Investment properties valuation reversal of past losses', 'asset', 'fixed_assets_tangible', '627', true),
  ('628', 'Investment properties cost impairments b/fwd', 'asset', 'fixed_assets_tangible', null, true),
  ('628.01', 'Investment properties cost impairment losses', 'asset', 'fixed_assets_tangible', '628', true),
  ('628.02', 'Investment properties cost reversals of past losses', 'asset', 'fixed_assets_tangible', '628', true),
  ('629', 'Investment properties accumulated depreciation b/fwd', 'asset', 'fixed_assets_tangible', null, true),
  ('629.01', 'Investment properties depreciation charge for the period', 'asset', 'fixed_assets_tangible', '629', true),
  ('629.02', 'Investment properties depreciation elimination on disposal', 'asset', 'fixed_assets_tangible', '629', true),
  ('629.03', 'Investment properties depreciation transfer to/from other category', 'asset', 'fixed_assets_tangible', '629', true),
  ('629.04', 'Investment properties depreciation write-back on revaluation', 'asset', 'fixed_assets_tangible', '629', true),
  ('629.05', 'Investment properties foreign currency exchange difference depreciation', 'asset', 'fixed_assets_tangible', '629', true),
  ('631', 'Leasehold property', 'asset', 'fixed_assets_tangible', null, true),
  ('631.01', 'Long leasehold additions at cost', 'asset', 'fixed_assets_tangible', '631', true),
  ('631.02', 'Long leasehold surplus on revaluation in period', 'asset', 'fixed_assets_tangible', '631', true),
  ('631.03', 'Long leasehold cost or valuation of disposal', 'asset', 'fixed_assets_tangible', '631', true),
  ('631.04', 'Long leasehold transfer to/from other category', 'asset', 'fixed_assets_tangible', '631', true),
  ('631.05', 'Long leasehold foreign currency exchange difference cost', 'asset', 'fixed_assets_tangible', '631', true),
  ('631.06', 'Long leasehold additions accruals', 'asset', 'fixed_assets_tangible', '631', true),
  ('632', 'Depreciation on leasehold improvements', 'asset', 'fixed_assets_tangible', null, true),
  ('632.01', 'Long leasehold amortisation charge for period', 'asset', 'fixed_assets_tangible', '632', true),
  ('632.02', 'Long leasehold amortisation elimination on revaluation', 'asset', 'fixed_assets_tangible', '632', true),
  ('632.03', 'Long leasehold amortisation elimination on disposal', 'asset', 'fixed_assets_tangible', '632', true),
  ('632.04', 'Long leasehold amortisation transfer to/from other category', 'asset', 'fixed_assets_tangible', '632', true),
  ('632.05', 'Long leasehold foreign currency exchange difference depreciation', 'asset', 'fixed_assets_tangible', '632', true),
  ('633', 'Long leasehold cost impairments b/fwd', 'asset', 'fixed_assets_tangible', null, true),
  ('633.01', 'Long leasehold cost impairment losses', 'asset', 'fixed_assets_tangible', '633', true),
  ('633.02', 'Long leasehold cost reversals of past losses', 'asset', 'fixed_assets_tangible', '633', true),
  ('634', 'Long leasehold valuation impairments b/fwd', 'asset', 'fixed_assets_tangible', null, true),
  ('634.01', 'Long leasehold valuation impairment losses', 'asset', 'fixed_assets_tangible', '634', true),
  ('634.02', 'Long leasehold valuation reversal of past losses', 'asset', 'fixed_assets_tangible', '634', true),
  ('641', 'Short leasehold cost or valuation b/fwd', 'asset', 'fixed_assets_tangible', null, true),
  ('641.01', 'Short leasehold additions at cost', 'asset', 'fixed_assets_tangible', '641', true),
  ('641.02', 'Short leasehold surplus on revaluation in year', 'asset', 'fixed_assets_tangible', '641', true),
  ('641.03', 'Short leasehold cost or valuation on disposal', 'asset', 'fixed_assets_tangible', '641', true),
  ('642', 'Short leasehold accumulated amortisation b/fwd', 'asset', 'fixed_assets_tangible', null, true),
  ('642.01', 'Short leasehold amortisation charge for period', 'asset', 'fixed_assets_tangible', '642', true),
  ('642.02', 'Short leasehold amortisation elimination on revaluation', 'asset', 'fixed_assets_tangible', '642', true),
  ('642.03', 'Short leasehold amortisation elimination on disposal', 'asset', 'fixed_assets_tangible', '642', true),
  ('651', 'Plant and machinery', 'asset', 'fixed_assets_tangible', null, true),
  ('651.01', 'Plant and machinery additions at cost', 'asset', 'fixed_assets_tangible', '651', true),
  ('651.02', 'Plant and machinery cost or valuation of disposals', 'asset', 'fixed_assets_tangible', '651', true),
  ('651.03', 'Plant and machinery transfer to/from other category', 'asset', 'fixed_assets_tangible', '651', true),
  ('651.04', 'Plant and machinery revaluation in period', 'asset', 'fixed_assets_tangible', '651', true),
  ('651.05', 'Plant and machinery foreign currency exchange difference cost', 'asset', 'fixed_assets_tangible', '651', true),
  ('651.06', 'Plant and machinery additions accruals', 'asset', 'fixed_assets_tangible', '651', true),
  ('652', 'Depreciation on plant and machinery', 'asset', 'fixed_assets_tangible', null, true),
  ('652.01', 'Plant and machinery depreciation charge for period', 'asset', 'fixed_assets_tangible', '652', true),
  ('652.02', 'Plant and machinery depreciation elimination on disposal', 'asset', 'fixed_assets_tangible', '652', true),
  ('652.03', 'Plant and machinery depreciation transfer to/from other category', 'asset', 'fixed_assets_tangible', '652', true),
  ('652.04', 'Plant and machinery depreciation write-back on revaluation', 'asset', 'fixed_assets_tangible', '652', true),
  ('653', 'Plant and machinery cost impairments b/fwd', 'asset', 'fixed_assets_tangible', null, true),
  ('653.01', 'Plant and machinery cost impairment losses', 'asset', 'fixed_assets_tangible', '653', true),
  ('653.02', 'Plant and machinery cost reversal of past losses', 'asset', 'fixed_assets_tangible', '653', true),
  ('654', 'Plant and machinery valuation impairments b/fwd', 'asset', 'fixed_assets_tangible', null, true),
  ('654.01', 'Plant and machinery valuation impairment losses', 'asset', 'fixed_assets_tangible', '654', true),
  ('654.02', 'Plant and machinery valuation reversal of past losses', 'asset', 'fixed_assets_tangible', '654', true),
  ('654.03', 'Plant and machinery foreign currency exchange difference depreciation', 'asset', 'fixed_assets_tangible', '654', true),
  ('661', 'Fixtures, fittings and equipment', 'asset', 'fixed_assets_tangible', null, true),
  ('661.01', 'Fixtures, fittings and equipment additions at cost', 'asset', 'fixed_assets_tangible', '661', true),
  ('661.02', 'Fixtures, fittings and equipment cost of disposals', 'asset', 'fixed_assets_tangible', '661', true),
  ('661.03', 'Fixtures, fittings and equipment transfer to/from other category', 'asset', 'fixed_assets_tangible', '661', true),
  ('661.04', 'Fixtures, fittings and equipment foreign currency exchange difference cost', 'asset', 'fixed_assets_tangible', '661', true),
  ('661.06', 'Fixtures, fittings and equipment additions accruals', 'asset', 'fixed_assets_tangible', '661', true),
  ('662', 'Depreciation on fixtures, fittings and equipment', 'asset', 'fixed_assets_tangible', null, true),
  ('662.01', 'Fixtures, fittings and equipment depreciation charge for period', 'asset', 'fixed_assets_tangible', '662', true),
  ('662.02', 'Fixtures, fittings and equipment depreciation on disposals', 'asset', 'fixed_assets_tangible', '662', true),
  ('662.03', 'Fixtures, fittings and equipment depreciation on transfer to/from other category', 'asset', 'fixed_assets_tangible', '662', true),
  ('662.04', 'Fixtures, fittings and equipment foreign currency exchange difference depreciation', 'asset', 'fixed_assets_tangible', '662', true),
  ('663', 'Fixtures, fittings and equipment cost impairments b/fwd', 'asset', 'fixed_assets_tangible', null, true),
  ('663.01', 'Fixtures, fittings and equipment cost impairment losses', 'asset', 'fixed_assets_tangible', '663', true),
  ('663.02', 'Fixtures, fittings and equipment cost reversal of past losses', 'asset', 'fixed_assets_tangible', '663', true),
  ('671', 'Motor vehicles', 'asset', 'fixed_assets_tangible', null, true),
  ('671.01', 'Motor vehicles additions at cost', 'asset', 'fixed_assets_tangible', '671', true),
  ('671.02', 'Motor vehicles cost of disposals', 'asset', 'fixed_assets_tangible', '671', true),
  ('671.03', 'Motor vehicles transfer to/from other category', 'asset', 'fixed_assets_tangible', '671', true),
  ('671.04', 'Motor vehicles foreign currency exchange difference cost', 'asset', 'fixed_assets_tangible', '671', true),
  ('671.06', 'Motor vehicles additions accruals', 'asset', 'fixed_assets_tangible', '671', true),
  ('672', 'Depreciation on motor vehicles', 'asset', 'fixed_assets_tangible', null, true),
  ('672.01', 'Motor vehicles depreciation charge for period', 'asset', 'fixed_assets_tangible', '672', true),
  ('672.02', 'Motor vehicles depreciation elimination on disposals', 'asset', 'fixed_assets_tangible', '672', true),
  ('672.03', 'Motor vehicles depreciation transfer to/from other category', 'asset', 'fixed_assets_tangible', '672', true),
  ('672.04', 'Motor vehicles foreign currency exchange difference depreciation', 'asset', 'fixed_assets_tangible', '672', true),
  ('673', 'Motor vehicles cost impairments b/fwd', 'asset', 'fixed_assets_tangible', null, true),
  ('673.01', 'Motor vehicles cost impairment losses', 'asset', 'fixed_assets_tangible', '673', true),
  ('673.02', 'Motor vehicles cost reversal of past losses', 'asset', 'fixed_assets_tangible', '673', true),
  ('681', 'Shares in subsidiary undertakings cost b/fwd', 'asset', 'fixed_assets_investments', null, true),
  ('681.01', 'Shares in subsidiary undertakings additions', 'asset', 'fixed_assets_investments', '681', true),
  ('681.02', 'Shares in subsidiary undertakings disposals', 'asset', 'fixed_assets_investments', '681', true),
  ('681.03', 'Shares in subsidiary undertakings revaluations', 'asset', 'fixed_assets_investments', '681', true),
  ('682', 'Shares in subsidiary undertakings provision for diminution b/fwd', 'asset', 'fixed_assets_investments', null, true),
  ('682.01', 'Shares in subsidiary undertakings provision for diminution movement', 'asset', 'fixed_assets_investments', '682', true),
  ('682.02', 'Shares in subsidiary undertakings provision for diminution disposals', 'asset', 'fixed_assets_investments', '682', true),
  ('686', 'Listed investments cost b/fwd', 'asset', 'fixed_assets_investments', null, true),
  ('686.01', 'Listed investments additions', 'asset', 'fixed_assets_investments', '686', true),
  ('686.02', 'Listed investments disposals', 'asset', 'fixed_assets_investments', '686', true),
  ('686.03', 'Listed investments revaluations', 'asset', 'fixed_assets_investments', '686', true),
  ('687', 'Listed investments provision for diminution b/fwd', 'asset', 'fixed_assets_investments', null, true),
  ('687.01', 'Listed investments provision for diminution movement', 'asset', 'fixed_assets_investments', '687', true),
  ('687.02', 'Listed investments provision for diminution disposal', 'asset', 'fixed_assets_investments', '687', true),
  ('701', 'Stock of finished goods', 'asset', 'stocks', null, true),
  ('701.01', 'Stock (non trading)', 'asset', 'stocks', '701', true),
  ('702', 'Raw materials', 'asset', 'stocks', null, true),
  ('702.01', 'Consumables', 'asset', 'stocks', '702', true),
  ('703', 'Work-in-progress', 'asset', 'stocks', null, true),
  ('704', 'Contract work-in-progress - long term', 'asset', 'stocks', null, true),
  ('705', 'Progress payments received on account re long term work-in-progress', 'asset', 'stocks', null, true),
  ('706', 'Amounts recoverable on long term work-in-progress', 'asset', 'debtors', null, true),
  ('711', 'Sales ledger control', 'asset', 'debtors', null, true),
  ('712', 'Trade debtors', 'asset', 'debtors', null, true),
  ('713', 'Purchase ledger debit balances', 'asset', 'debtors', null, true),
  ('715', 'Bad debt provision', 'asset', 'debtors', null, true),
  ('718', 'Finance amounts owed by group company 1', 'asset', 'debtors', null, true),
  ('724', 'Trading amounts owed by related parties', 'asset', 'debtors', null, true),
  ('725', 'Finance amounts owed by connected party 1', 'asset', 'debtors', null, true),
  ('726', 'Trading amounts owed by connected party 1', 'asset', 'debtors', null, true),
  ('728', 'Income tax recoverable', 'asset', 'debtors', null, true),
  ('729', 'Deferred tax asset', 'asset', 'debtors', null, true),
  ('730', 'Dividends receivable', 'asset', 'debtors', null, true),
  ('731', 'Advance Corporation Tax recoverable', 'asset', 'debtors', null, true),
  ('732', 'Other debtors', 'asset', 'debtors', null, true),
  ('733', 'Staff loans', 'asset', 'debtors', null, true),
  ('734', 'Corporation tax repayable', 'asset', 'debtors', null, true),
  ('735', 'Corporation tax recovered in year', 'asset', 'debtors', null, true),
  ('736', 'VAT repayable', 'asset', 'debtors', null, true),
  ('737', 'Called up share capital not paid', 'asset', 'debtors', null, true),
  ('738', 'Relevant Contracts Tax repayable', 'asset', 'debtors', null, true),
  ('739', 'PAYE prepaid', 'asset', 'debtors', null, true),
  ('739.01', 'NI/PRSI prepaid', 'asset', 'debtors', '739', true),
  ('740', 'Subcontractors tax', 'asset', 'debtors', null, true),
  ('740.01', 'Withholding tax', 'asset', 'debtors', '740', true),
  ('740.02', 'Environmental bag levy', 'asset', 'debtors', '740', true),
  ('740.03', 'User defined taxation debtor', 'asset', 'debtors', '740', true),
  ('741', 'Directors current accounts', 'asset', 'debtors', null, true),
  ('741.01', 'Director 2 current account (debtor)', 'asset', 'debtors', '741', true),
  ('746', 'User defined debtor', 'asset', 'debtors', null, true),
  ('748', 'Retained Tax Control', 'asset', 'debtors', null, true),
  ('751', 'Prepayments', 'asset', 'debtors', null, true),
  ('761', 'Cash equivalent investments b/fwd', 'asset', 'debtors', null, true),
  ('761.01', 'Cash equivalent investments additions', 'asset', 'debtors', '761', true),
  ('761.02', 'Cash equivalent investments disposals', 'asset', 'debtors', '761', true),
  ('761.03', 'Cash equivalent investments write-off/down', 'asset', 'debtors', '761', true),
  ('771', 'Bank current account', 'asset', 'cash', null, true),
  ('771.01', 'Bank current account 2', 'asset', 'cash', '771', true),
  ('777', 'Bank deposit account', 'asset', 'cash', null, true),
  ('781', 'Petty cash account', 'asset', 'cash', null, true),
  ('782', 'Cash control account', 'asset', 'cash', null, true),
  ('785', 'Client bank balances', 'asset', 'cash', null, true),
  ('801', 'Bank overdraft 1', 'liability', 'creditors_within_1y', null, true),
  ('801.01', 'Bank overdraft 2', 'liability', 'creditors_within_1y', '801', true),
  ('802', 'Client bank overdraft', 'liability', 'creditors_within_1y', null, true),
  ('807', 'Bank loan short term b/fwd', 'liability', 'creditors_within_1y', null, true),
  ('807.01', 'Bank loan short term increase', 'liability', 'creditors_within_1y', '807', true),
  ('807.02', 'Bank loan short term repayments', 'liability', 'creditors_within_1y', '807', true),
  ('807.03', 'Bank loan short term receipt of long term', 'liability', 'creditors_within_1y', '807', true),
  ('807.04', 'Bank loan short term repayment of long term', 'liability', 'creditors_within_1y', '807', true),
  ('807.05', 'Bank loan movement from long term', 'liability', 'creditors_within_1y', '807', true),
  ('811', 'Amounts received on account', 'liability', 'creditors_within_1y', null, true),
  ('812', 'Purchase ledger control', 'liability', 'creditors_within_1y', null, true),
  ('813', 'Trade creditors - posting account', 'liability', 'creditors_within_1y', null, true),
  ('814', 'Sales ledger credit balances', 'liability', 'creditors_within_1y', null, true),
  ('815', 'Bills of exchange', 'liability', 'creditors_within_1y', null, true),
  ('818', 'Finance amounts due to group company 1', 'liability', 'creditors_within_1y', null, true),
  ('819', 'Trading amounts due to group company 1', 'liability', 'creditors_within_1y', null, true),
  ('821', 'Finance amounts due to related parties', 'liability', 'creditors_within_1y', null, true),
  ('821.01', 'Trading amounts due to related parties', 'liability', 'creditors_within_1y', '821', true),
  ('822', 'Finance amounts due to connected party 1', 'liability', 'creditors_within_1y', null, true),
  ('823', 'Trading amounts due to connected party 1', 'liability', 'creditors_within_1y', null, true),
  ('831', 'Corporation tax payable', 'liability', 'creditors_within_1y', null, true),
  ('832', 'Corporation tax paid', 'liability', 'creditors_within_1y', null, true),
  ('833', 'Corporation tax repaid', 'liability', 'creditors_within_1y', null, true),
  ('834', 'Advance Corporation Tax payable', 'liability', 'creditors_within_1y', null, true),
  ('835', 'Advance Corporation Tax paid', 'liability', 'creditors_within_1y', null, true),
  ('836', 'Relevant Contracts Tax payable', 'liability', 'creditors_within_1y', null, true),
  ('837', 'Tax credits', 'liability', 'creditors_within_1y', null, true),
  ('841', 'Excise duty', 'liability', 'creditors_within_1y', null, true),
  ('842', 'Environmental bag levy', 'liability', 'creditors_within_1y', null, true),
  ('843', 'Subcontractors, withholding and other taxes', 'liability', 'creditors_within_1y', null, true),
  ('844', 'Withholding tax', 'liability', 'creditors_within_1y', null, true),
  ('845', 'VAT control account', 'liability', 'creditors_within_1y', null, true),
  ('846', 'PAYE control account', 'liability', 'creditors_within_1y', null, true),
  ('847', 'PAYE on directors'' bonuses', 'liability', 'creditors_within_1y', null, true),
  ('848', 'NIC (UK) PRSI (Ireland) control account', 'liability', 'creditors_within_1y', null, true),
  ('849', 'User-defined taxation creditor', 'liability', 'creditors_within_1y', null, true),
  ('851', 'HP liability payable', 'liability', 'creditors_within_1y', null, true),
  ('852', 'HP interest suspense < 1 year', 'liability', 'creditors_within_1y', null, true),
  ('853', 'Lease obligations payable', 'liability', 'creditors_within_1y', null, true),
  ('854', 'Lease interest suspense < 1 year', 'liability', 'creditors_within_1y', null, true),
  ('861', 'Director 1 current account (creditor)', 'liability', 'creditors_within_1y', null, true),
  ('861.01', 'Director 2 current account (creditor)', 'liability', 'creditors_within_1y', '861', true),
  ('871', 'Wages and salaries control', 'liability', 'creditors_within_1y', null, true),
  ('880', 'Other creditors', 'liability', 'creditors_within_1y', null, true),
  ('881', 'Accruals', 'liability', 'creditors_within_1y', null, true),
  ('881.01', 'Fixed assets accruals', 'liability', 'creditors_within_1y', '881', true),
  ('881.02', 'Dividend accruals', 'liability', 'creditors_within_1y', '881', true),
  ('883', 'Current deferred income', 'liability', 'creditors_within_1y', null, true),
  ('893', 'Shares classified as financial liabilities < 1 year b/fwd', 'liability', 'creditors_within_1y', null, true),
  ('893.01', 'Shares classified as financial liabilities < 1 year cash issue', 'liability', 'creditors_within_1y', '893', true),
  ('893.02', 'Shares classified as financial liabilities < 1 year movement from long term', 'liability', 'creditors_within_1y', '893', true),
  ('893.03', 'Shares classified as financial liabilities < 1 year redemption of shares', 'liability', 'creditors_within_1y', '893', true),
  ('904', 'Bank loan balance', 'liability', 'creditors_after_1y', null, true),
  ('904.01', 'Long term bank loan increase', 'liability', 'creditors_after_1y', '904', true),
  ('904.02', 'Long term bank loan movement to under 1 year', 'liability', 'creditors_after_1y', '904', true),
  ('904.03', 'Long term bank loan amortisation using effective rate of return', 'liability', 'creditors_after_1y', '904', true),
  ('911', 'Finance amounts due to related parties', 'liability', 'creditors_after_1y', null, true),
  ('912', 'Trading amounts due to related parties', 'liability', 'creditors_after_1y', null, true),
  ('913', 'Trading amounts owed to group companies > 1 year', 'liability', 'creditors_after_1y', null, true),
  ('914', 'Trading amounts owed to connected companies > 1 year', 'liability', 'creditors_after_1y', null, true),
  ('915', 'Finance amounts owed to group companies > 1 year', 'liability', 'creditors_after_1y', null, true),
  ('916', 'Finance amounts owed to connected companies > 1 year', 'liability', 'creditors_after_1y', null, true),
  ('917', 'Directors loan accounts', 'liability', 'creditors_after_1y', null, true),
  ('917.01', 'Director 1 loan account > 1 year movement', 'liability', 'creditors_after_1y', '917', true),
  ('917.02', 'Director 2 loan account > 1 year b/fwd', 'liability', 'creditors_after_1y', '917', true),
  ('917.03', 'Director 2 loan account > 1 year movement', 'liability', 'creditors_after_1y', '917', true),
  ('918', 'Taxation and social welfare > 1 year b/fwd', 'liability', 'creditors_after_1y', null, true),
  ('918.01', 'Taxation and social welfare > 1 year movement', 'liability', 'creditors_after_1y', '918', true),
  ('919', 'Other loans due > 1 year b/fwd', 'liability', 'creditors_after_1y', null, true),
  ('919.01', 'Other loans due > 1 year movement', 'liability', 'creditors_after_1y', '919', true),
  ('919.02', 'Other loans due > 1 year amortisation using effective rate of return', 'liability', 'creditors_after_1y', '919', true),
  ('921', 'Hire purchase liability balance', 'liability', 'creditors_after_1y', null, true),
  ('921.01', 'Long term HP liability increase', 'liability', 'creditors_after_1y', '921', true),
  ('921.02', 'Long term HP repayments', 'liability', 'creditors_after_1y', '921', true),
  ('922', 'Finance lease obligations', 'liability', 'creditors_after_1y', null, true),
  ('922.01', 'Long term lease obligations increase', 'liability', 'creditors_after_1y', '922', true),
  ('922.02', 'Long term lease obligations repaid', 'liability', 'creditors_after_1y', '922', true),
  ('928', 'Shares classified as financial liabilities > 1 year b/fwd', 'liability', 'creditors_after_1y', null, true),
  ('928.01', 'Shares classified as financial liabilities > 1 year cash issue', 'liability', 'creditors_after_1y', '928', true),
  ('928.02', 'Shares classified as financial liabilities > 1 year movement to short term', 'liability', 'creditors_after_1y', '928', true),
  ('928.03', 'Shares classified as financial liabilities > 1 year redemption of shares', 'liability', 'creditors_after_1y', '928', true),
  ('931', 'Deferred tax re capital allowances b/fwd', 'liability', 'provisions', null, true),
  ('931.01', 'Deferred tax re capital allowances charge for the year', 'liability', 'provisions', '931', true),
  ('931.02', 'Deferred tax re capital allowances utilised in year', 'liability', 'provisions', '931', true),
  ('931.03', 'Deferred tax re capital allowances released', 'liability', 'provisions', '931', true),
  ('931.04', 'Deferred tax re capital allowances charged to reserves', 'liability', 'provisions', '931', true),
  ('940', 'Other provisions b/fwd', 'liability', 'provisions', null, true),
  ('940.01', 'Other provisions charge for the year', 'liability', 'provisions', '940', true),
  ('940.02', 'Other provisions utilisation in the year', 'liability', 'provisions', '940', true),
  ('940.03', 'Other provisions released', 'liability', 'provisions', '940', true),
  ('940.04', 'Other provisions charged to reserves', 'liability', 'provisions', '940', true),
  ('948', 'Directors'' defined benefit pension asset b/fwd', 'asset', 'debtors', null, true),
  ('948.01', 'Directors'' defined benefit pension asset movement', 'asset', 'debtors', '948', true),
  ('949', 'Staff defined benefit pension asset b/fwd', 'asset', 'debtors', null, true),
  ('949.01', 'Staff defined benefit pension asset movement', 'asset', 'debtors', '949', true),
  ('999', 'Balance sheet suspense', 'asset', 'debtors', null, true),
  ('951', 'Ordinary equity share capital', 'equity', 'share_capital', null, true),
  ('951.01', 'Ordinary equity share capital class 1 cash issue', 'equity', 'share_capital', '951', true),
  ('951.02', 'Ordinary equity share capital class 1 bonus issue', 'equity', 'share_capital', '951', true),
  ('951.03', 'Ordinary equity share capital class 1 redemption of shares', 'equity', 'share_capital', '951', true),
  ('951.04', 'Ordinary equity share capital class 1 equity-settled share-based payment issue', 'equity', 'share_capital', '951', true),
  ('961', 'Preference equity share capital class', 'equity', 'share_capital', null, true),
  ('961.01', 'Preference equity share capital class 1 cash issue', 'equity', 'share_capital', '961', true),
  ('961.02', 'Preference equity share capital class 1 bonus issue', 'equity', 'share_capital', '961', true),
  ('961.03', 'Preference equity share capital class 1 redemption of shares', 'equity', 'share_capital', '961', true),
  ('961.04', 'Preference equity share capital class 1 equity-settled share-based payment issue', 'equity', 'share_capital', '961', true),
  ('967', 'Share premium on preference equity shares', 'equity', 'share_capital', null, true),
  ('971', 'Share premium on ordinary equity shares', 'equity', 'share_capital', null, true),
  ('975', 'Revaluation reserve', 'equity', 'reserves', null, true),
  ('975.01', 'Revaluation reserve transfer of realised profit', 'equity', 'reserves', '975', true),
  ('975.02', 'Revaluation reserve unrealised movement on revaluation of property', 'equity', 'reserves', '975', true),
  ('975.03', 'Revaluation reserve property deferred tax', 'equity', 'reserves', '975', true),
  ('975.04', 'Revaluation reserve other movement', 'equity', 'reserves', '975', true),
  ('975.05', 'Revaluation reserve impairment losses', 'equity', 'reserves', '975', true),
  ('975.06', 'Revaluation reserve reversal of past impairment losses', 'equity', 'reserves', '975', true),
  ('976', 'User-defined reserve 1 b/fwd', 'equity', 'reserves', null, true),
  ('976.01', 'User-defined reserve 1 movement', 'equity', 'reserves', '976', true),
  ('976.02', 'User-defined reserve 1 movement to/from cash-based operating profit account', 'equity', 'reserves', '976', true),
  ('531', 'Retained profit - dividends on ordinary equity share', 'equity', 'profit_loss_account', null, true),
  ('531.01', 'Final dividends paid - ordinary equity class 1 (movement on reserve)', 'equity', 'profit_loss_account', '531', true),
  ('531.02', 'Final dividends accrued - ordinary equity class 1 (if approved during year) (movement on reserve)', 'equity', 'profit_loss_account', '531', true),
  ('531.03', 'Final Dividends proposed paid after one year or similar', 'equity', 'profit_loss_account', '531', true),
  ('532', 'Interim dividends paid - ordinary equity class 2 (movement on reserve)', 'equity', 'profit_loss_account', null, true),
  ('532.01', 'Final dividends paid - ordinary equity class 2 (movement on reserve)', 'equity', 'profit_loss_account', '532', true),
  ('532.02', 'Final dividends accrued - ordinary equity class 2 (if approved during year) (movement on reserve)', 'equity', 'profit_loss_account', '532', true),
  ('533', 'Retained profit - dividends on preference equity share', 'equity', 'profit_loss_account', null, true),
  ('533.01', 'Final dividends paid - preference equity shares (movement on reserve; if financial charge use 487)', 'equity', 'profit_loss_account', '533', true),
  ('533.02', 'Final dividends accrued - preference equity shares (movement on reserve)', 'equity', 'profit_loss_account', '533', true),
  ('991', 'Retained profit - brought forward', 'equity', 'profit_loss_account', null, true),
  ('991.01', 'Profit and loss reserve prior year adjustment', 'equity', 'profit_loss_account', '991', true),
  ('991.02', 'Profit and loss reserve reserve goodwill write off', 'equity', 'profit_loss_account', '991', true),
  ('991.03', 'Profit and loss reserve transfer from another reserve', 'equity', 'profit_loss_account', '991', true),
  ('991.04', 'Profit and loss reserve taxation on realised revaluation gains', 'equity', 'profit_loss_account', '991', true),
  ('991.05', 'Profit and loss reserve foreign exchange difference on net investments', 'equity', 'profit_loss_account', '991', true),
  ('991.06', 'Directors'' defined benefit actuarial gain/(loss) re FRS 17 or remeasurement re FRS 102', 'equity', 'profit_loss_account', '991', true),
  ('991.07', 'Staff defined benefit actuarial gain/(loss) re FRS 17 or remeasurement re FRS 102', 'equity', 'profit_loss_account', '991', true),
  ('991.08', 'Other defined benefit actuarial gain/(loss) re FRS 17 or remeasurement re FRS 102', 'equity', 'profit_loss_account', '991', true),
  ('991.09', 'Profit and loss reserve other movement', 'equity', 'profit_loss_account', '991', true),
  ('991.10', 'Profit and loss reserve preference share appropriations (if financial liability use 487)', 'equity', 'profit_loss_account', '991', true),
  ('991.11', 'Profit and loss reserve re-nominalisation of share capital', 'equity', 'profit_loss_account', '991', true),
  ('991.12', 'Profit and loss reserve redemption of shares', 'equity', 'profit_loss_account', '991', true),
  ('991.13', 'Profit and loss reserve gain or loss on hedging instruments re net assets of foreign operations', 'equity', 'profit_loss_account', '991', true),
  ('995', 'Directors'' defined benefit pension reserve b/fwd', 'equity', 'profit_loss_account', null, true),
  ('995.01', 'Directors'' defined benefit pension reserve movement', 'equity', 'profit_loss_account', '995', true),
  ('996', 'Staff defined benefit pension reserve b/fwd', 'equity', 'profit_loss_account', null, true),
  ('996.01', 'Staff defined benefit pension reserve movement', 'equity', 'profit_loss_account', '996', true),
  ('997', 'Other defined benefit pension reserve b/fwd', 'equity', 'profit_loss_account', null, true),
  ('997.01', 'Other defined benefit pension reserve movement', 'equity', 'profit_loss_account', '997', true)
on conflict (code) where client_id is null do update
  set description = excluded.description,
      type = excluded.type,
      report_group = excluded.report_group,
      parent_code = excluded.parent_code,
      postable = excluded.postable,
      active = true;

-- 2. O MAPA DAS ANTIGAS ---------------------------------------------------
--
-- Escrito a mao, olhando para a seccao de destino. Emparelhar por semelhanca
-- de texto foi tentado e produziu erros graves — "Rent and rates" ia parar a
-- "Rent receivable", que e RECEITA. Num plano de contas, um emparelhamento
-- errado nao da erro: da um balanco plausivel e falso.
create temporary table _mapa_plano (velho text primary key, novo text not null);
insert into _mapa_plano (velho, novo) values
    ('1100', '771'),
    ('1110', '781'),
    ('1200', '711'),
    ('1300', '736'),
    ('1400', '751'),
    ('1500', '701'),
    ('1600', '651'),
    ('1690', '392'),
    ('2100', '812'),
    ('2200', '845'),
    ('2300', '846'),
    ('2400', '871'),
    ('2500', '881'),
    ('2600', '904'),
    ('2900', '831'),
    ('3100', '951'),
    ('3200', '991'),
    ('4100', '001'),
    ('4200', '076'),
    ('4900', '081'),
    ('5100', '112'),
    ('5200', '111'),
    ('6100', '322'),
    ('6200', '116'),
    ('6300', '371'),
    ('6400', '345'),
    ('6500', '331'),
    ('6600', '326'),
    ('6700', '346'),
    ('6750', '341'),
    ('6800', '114'),
    ('6850', '334'),
    ('6900', '365'),
    ('6910', '342'),
    ('6950', '301'),
    ('6960', '303'),
    ('6990', '381'),
    ('7100', '471'),
    ('7200', '377'),
    ('8100', '501'),
    ('9999', '999');

-- 3. LEVAR O QUE JA ESTA LANCADO PARA OS CODIGOS NOVOS --------------------
--
-- A ordem nao importa entre estas, mas TODAS tem de correr: uma tabela
-- esquecida fica a apontar para uma conta inativa, e o saldo dela sai dos
-- relatorios sem aviso.
update journal_lines jl set account_code = m.novo
  from _mapa_plano m where jl.account_code = m.velho;

update ledger_items li set account_code = m.novo
  from _mapa_plano m where li.account_code = m.velho;

update sales s set account_code = m.novo
  from _mapa_plano m where s.account_code = m.velho;

update bank_accounts b set account_code = m.novo
  from _mapa_plano m where b.account_code = m.velho;

update client_item_accounts c set account_code = m.novo
  from _mapa_plano m where c.account_code = m.velho;

-- 4. AS ANTIGAS SAEM DE CIRCULACAO ----------------------------------------
update chart_of_accounts set active = false
where client_id is null and code in (select velho from _mapa_plano);

drop table _mapa_plano;
